### ISSUE TITLE
can't start greetservice in Vaadin 20 alpha 7 if Java 11 language features are turned on

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/base-starter-flow-karaf#35]
If you check out [this branch](https://github.com/vaadin/base-starter-flow-karaf/tree/feature/java-11-lang-features) that has Java 11 enabled (which probably should be as there is no reason to stay in Java 8 as latest Karaf only supports Java 11), build the project with "mvn install" and follow the tutorial steps in the README.md in the top level project, the greetservice-impl module refuses to start:

```
 Error executing command: Error executing command on bundles:
	Error starting bundle 192: Unable to resolve greetservice-impl [192](R 192.1): missing requirement [greetservice-impl [192](R 192.1)] osgi.wiring.package; (osgi.wiring.package=java.lang.invoke) Unresolved requirements: [[greetservice-impl [192](R 192.1)] osgi.wiring.package; (osgi.wiring.package=java.lang.invoke)]
```

My environment:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/local/share/java/maven3
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Users/sebastian/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by Maurice-Betzel** [comment]
The dependency on the Vaadin root pom brings some side effects.  Either suppress the import in the bnd file:
`Import-Package: !java.*,*`
Or decouple the service by creating a API bundle, adding this to the starter pom, and remove the base starter parent.

**Comment by SebastianKuehnau** [comment]
If I leave the properties for `maven.compiler.source` and `maven.compiler.target` on `1.8` it is working correctly (no matter I build with JDK 8 or 11)

The error only occur after changing the properties to `11` in the base starter parent.

**Comment by denis-anisimov** [comment]
Java version :
```
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode
```

Can't reproduce it with it.

**Comment by mstahv** [comment]
Yup, can be reproduced if the Java version is upped to 11 in the pom.xml. Modified the description a bit.

**Comment by mstahv** [comment]
@Maurice-Betzel Do you think the solution in the linked PR is right? Is the `Import-Package: !java.*,*`import hint now required for basically all bundles if built using Java 11?

I have the better modularisation in works as well, but that alone didn't fix it so progressing one step at the time...
