### ISSUE TITLE
Use push to show the newly added views to the user

### ISSUE THREAD

**Issue by pleku** [vaadin/base-starter-flow-karaf#6]
When a new bundle with views (routes) is deployed, the added view menu item should be pushed to existing UIs.
Similarly, when a bundle is removed, any menu items that are for views in the removed bundle should be removed and updates pushed to users. If a user had opened any of the removed view(s), the user(s) should be redirected/notified of the view not being available anymore instead of failing things.

**Comment by denis-anisimov** [comment]
> the user(s) should be redirected/notified of the view not being available anymore instead of failing things.

As many times said: when route is unregistered it's the same state as it's  being not registered.
`RouteNotFoundError`  generically handles the route not found event.

**Comment by pleku** [comment]
>    > the user(s) should be redirected/notified of the view not being available anymore instead of failing things.

> As many times said: when route is unregistered it's the same state as it's being not registered.
RouteNotFoundError generically handles the route not found event.

Yes, I think you've misunderstood my comment since it meant (like mentioned in the call) that any user who has the view open, should not be left with that view open but be redirected to the 404 view and the demo would be about pushing a notification for now like mentioned by @mstahv. I don't think the PRs changes do any redirect and show notification for the end user, which is not really that good UX if things just fail once they press a button.

**Comment by denis-anisimov** [comment]
yes, I misunderstood.
